# Generated by tiders codegen from polymarket_CTFExchange.yaml
# Project: polymarket_CTFExchange — Indexes the Polymarket Multiple-Choice Leading contract events
#
# This script ingests events from the Polymarket CTFExchange contract on Polygon
# and writes decoded event data to ClickHouse.
#
# The file is pre-configured with `from_block: 81053172` (2026-01-01 00:00:00) and `to_block: 81139570` (2026-01-02 23:59:59), 2 days worth of data. You can reduce the interval for a faster ingestion.
#
# Usage:
#   cd examples/polymarket_vol
#   python polymarket_ctfexchange.py
#
# After this and the NegRiskCtfExchange pipeline complete, run:
#   python polymarket_vol_transformation.py

import asyncio
from pathlib import Path

from tiders import run_pipeline
from tiders.config import (
    ClickHouseWriterConfig,
    EvmDecodeEventsConfig,
    EvmTableAliases,
    HexEncodeConfig,
    JoinBlockDataConfig,
    Pipeline,
    Step,
    StepKind,
    Writer,
    WriterKind,
)
from tiders_core.ingest import ProviderConfig, ProviderKind, Query, QueryKind
from tiders_core.ingest import evm
from tiders_core import evm_abi_events, evm_abi_functions


# Contract: polymarket_CTFExchange
polymarket_CTFExchange_abi_path = Path(
    "/home/yulesa/repos/tiders/examples/polymarket_vol/polymarket_CTFExchange.abi.json"
)
polymarket_CTFExchange_abi_json = polymarket_CTFExchange_abi_path.read_text()
polymarket_CTFExchange_events = {
    ev.name: {"topic0": ev.topic0, "signature": ev.signature}
    for ev in evm_abi_events(polymarket_CTFExchange_abi_json)
}
polymarket_CTFExchange_functions = {
    fn.name: {"selector": fn.selector, "signature": fn.signature}
    for fn in evm_abi_functions(polymarket_CTFExchange_abi_json)
}
polymarket_CTFExchange_address = "0x4bfb41d5b3570defd03c39a9a4d8de6bd8b8982e"


provider = ProviderConfig(
    kind=ProviderKind.SQD,
    url="https://portal.sqd.dev/datasets/polygon-mainnet",
)

query = Query(
    kind=QueryKind.EVM,
    params=evm.Query(
        from_block=81053172,
        to_block=81139570,
        logs=[
            evm.LogRequest(
                address=["0x4bfb41d5b3570defd03c39a9a4d8de6bd8b8982e"],
                topic0=[
                    "0xd0a08e8c493f9c94f29311604c9de1b4e8c8d4c06bd0c789af57f2d65bfec0f6",
                    "0x63bf4d16b7fa898ef4c4b2b6d90fd201e9c56313b65638af6088d149d2ce956c",
                    "0xbc9a2432e8aeb48327246cddd6e872ef452812b4243c04e6bfb786a2cd8faf0d",
                    "0x5152abf959f6564662358c2e52b702259b78bac5ee7842a0f01937e670efcc7d",
                    "0xacffcc86834d0f1a64b0d5a675798deed6ff0bcfc2231edd3480e7288dba7ff4",
                ],
                include_blocks=True,
            ),
        ],
        fields=evm.Fields(
            block=evm.BlockFields(
                number=True,
                hash=True,
                timestamp=True,
            ),
            log=evm.LogFields(
                log_index=True,
                transaction_index=True,
                transaction_hash=True,
                block_hash=True,
                block_number=True,
                address=True,
                data=True,
                topic0=True,
                topic1=True,
                topic2=True,
                topic3=True,
            ),
        ),
    ),
)

steps = [
    Step(
        kind=StepKind.EVM_DECODE_EVENTS,
        config=EvmDecodeEventsConfig(
            event_signature="OrderFilled(bytes32 indexed orderHash, address indexed maker, address indexed taker, uint256 makerAssetId, uint256 takerAssetId, uint256 makerAmountFilled, uint256 takerAmountFilled, uint256 fee)",
            allow_decode_fail=True,
            filter_by_topic0=True,
            input_table="polymarket_ctfexchange_logs",
            output_table="polymarket_ctfexchange_orderfilled",
        ),
    ),
    Step(
        kind=StepKind.EVM_DECODE_EVENTS,
        config=EvmDecodeEventsConfig(
            event_signature="OrdersMatched(bytes32 indexed takerOrderHash, address indexed takerOrderMaker, uint256 makerAssetId, uint256 takerAssetId, uint256 makerAmountFilled, uint256 takerAmountFilled)",
            allow_decode_fail=True,
            filter_by_topic0=True,
            input_table="polymarket_ctfexchange_logs",
            output_table="polymarket_ctfexchange_ordersmatched",
        ),
    ),
    Step(
        kind=StepKind.EVM_DECODE_EVENTS,
        config=EvmDecodeEventsConfig(
            event_signature="TokenRegistered(uint256 indexed token0, uint256 indexed token1, bytes32 indexed conditionId)",
            allow_decode_fail=True,
            filter_by_topic0=True,
            input_table="polymarket_ctfexchange_logs",
            output_table="polymarket_ctfexchange_tokenregistered",
        ),
    ),
    Step(
        kind=StepKind.EVM_DECODE_EVENTS,
        config=EvmDecodeEventsConfig(
            event_signature="OrderCancelled(bytes32 indexed orderHash)",
            allow_decode_fail=True,
            filter_by_topic0=True,
            input_table="polymarket_ctfexchange_logs",
            output_table="polymarket_ctfexchange_ordercancelled",
        ),
    ),
    Step(
        kind=StepKind.EVM_DECODE_EVENTS,
        config=EvmDecodeEventsConfig(
            event_signature="FeeCharged(address indexed receiver, uint256 tokenId, uint256 amount)",
            allow_decode_fail=True,
            filter_by_topic0=True,
            input_table="polymarket_ctfexchange_logs",
            output_table="polymarket_ctfexchange_feecharged",
        ),
    ),
    Step(
        kind=StepKind.JOIN_BLOCK_DATA,
        config=JoinBlockDataConfig(
            tables=[
                "polymarket_ctfexchange_orderfilled",
                "polymarket_ctfexchange_ordersmatched",
                "polymarket_ctfexchange_tokenregistered",
                "polymarket_ctfexchange_ordercancelled",
            ],
        ),
    ),
    Step(
        kind=StepKind.HEX_ENCODE,
        config=HexEncodeConfig(),
    ),
]

writer = Writer(
    kind=WriterKind.CLICKHOUSE,
    config=ClickHouseWriterConfig(password="default"),
)

table_aliases = EvmTableAliases(logs="polymarket_ctfexchange_logs")

pipeline = Pipeline(
    provider=provider,
    query=query,
    writer=writer,
    steps=steps,
    table_aliases=table_aliases,
)


if __name__ == "__main__":
    asyncio.run(run_pipeline(pipeline))
