name: Release

on:
  push:
    tags:
      - v*

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: sudo apt-get update && sudo apt-get install -y capnproto
      - run: uv build
      - run: uv publish --trusted-publishing always
